🌱 Use finelizers instead of ownerRefs to check if IPClaim is in use
metal3-io/ip-address-manager pull request #133
Opened 2022-09-01 12:08 UTC by lentzi90

**What this PR does / why we need it**:

The previous implementation was API breaking, since it required the
user/controller owning the IPClaim to remove the ownerRef before the
IPAddress would be deleted. This commit changes it so that we check for
finalizers instead. More specifically, if there are any other finalizers
than the IPAM one, we consider the IPClaim to be still in use. In this
way we "revert" the API breaking change but still get the same
functionality.

2022-09-01 12:13 UTC, lentzi90 commented
/test unit

2022-09-02 08:24 UTC, lentzi90 commented
/test-ubuntu-integration-main

2022-09-02 08:26 UTC, lentzi90 commented
/test-ubuntu-e2e-main

2022-09-02 09:47 UTC, lentzi90 commented
/test-upgrade-e2e-main

2022-09-02 11:27 UTC, kashifest approved these changes

2022-09-02 11:30 UTC, kashifest commented
/test-upgrade-e2e-main

2022-09-02 15:07 UTC, furkatgofurov7 commented
/test-upgrade-e2e-main

2022-09-02 15:59 UTC, furkatgofurov7 commented
/test-upgrade-e2e-main

2022-09-02 17:51 UTC, furkatgofurov7 requested changes

2022-09-02 17:51 UTC, furkatgofurov7 commented on ipam/ippool_manager.go
>  				"IPClaim", addressClaim.Name, "Owners", addressClaim.OwnerReferences)
```suggestion
				"IPClaim", addressClaim.Name, "Finalizers", addressClaim.Finalizers)
```

2022-09-02 17:51 UTC, furkatgofurov7 commented on ipam/ippool_manager.go
> +			(len(addressClaim.Finalizers) == 1 && !Contains(addressClaim.Finalizers, ipamv1.IPClaimFinalizer)) {
you could do:
```suggestion
		if len(addressClaim.Finalizers) >= 1 && !Contains(addressClaim.Finalizers, ipamv1.IPClaimFinalizer)) {
```

2022-09-03 08:33 UTC, furkatgofurov7 commented
/test-upgrade-e2e-main

2022-09-05 05:46 UTC, lentzi90 commented
/test unit

2022-09-05 06:27 UTC, lentzi90 commented
/test-ubuntu-integration-main

2022-09-05 07:08 UTC, furkatgofurov7 reviewed
/lgtm

2022-09-05 07:09 UTC, merged