🐛 Fix API version in IPAM webhooks
metal3-io/ip-address-manager pull request #53
Opened 2021-09-17 15:37 UTC by furkatgofurov7

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2021-09-17 15:46 UTC, furkatgofurov7 commented
/test-integration

2021-09-17 16:26 UTC, furkatgofurov7 commented
/test-centos-integration

2021-09-21 07:26 UTC, kashifest requested changes
Now that, I see it carefully, it seems this was a mistake all together. This should be versioned according to IPAM api version not CAPM3 api version. Would you like to change all of them in this PR?

2021-09-22 07:40 UTC, fmuyassarov commented
> Now that, I see it carefully, it seems this was a mistake all together. This should be versioned according to IPAM api version not CAPM3 api version. Would you like to change all of them in this PR?

I changed ipam api version to v1alpha1, since @furkatgofurov7 is on vacation.

2021-09-22 07:45 UTC, kashifest requested changes

2021-09-22 07:45 UTC, kashifest commented on api/v1alpha1/ipclaim_webhook.go
> +// +kubebuilder:webhook:verbs=create;update,path=/mutate-ipam-metal3-io-v1alphav-ipclaim,mutating=true,failurePolicy=fail,groups=ipam.metal3.io,resources=ipclaims,versions=v1alpha1,name=default.ipcla
typo?

2021-09-22 07:56 UTC, fmuyassarov commented on api/v1alpha1/ipclaim_webhook.go
> +// +kubebuilder:webhook:verbs=create;update,path=/mutate-ipam-metal3-io-v1alphav-ipclaim,mutating=true,failurePolicy=fail,groups=ipam.metal3.io,resources=ipclaims,versions=v1alpha1,name=default.ipcla
ops. yes

2021-09-22 08:04 UTC, kashifest commented
/test-integration
/test-centos-integration

2021-09-28 10:30 UTC, kashifest commented
/test-integration

2021-09-28 10:41 UTC, fmuyassarov commented
/test-integration

2021-09-28 10:45 UTC, fmuyassarov commented
/test-integration

2021-09-28 10:45 UTC, kashifest commented
/test-integration

2021-09-28 10:46 UTC, fmuyassarov commented
/test-integration

2021-09-28 11:02 UTC, kashifest commented
/test-centos-integration

2021-09-28 11:58 UTC, kashifest approved these changes
Thanks a lot @fmuyassarov and @furkatgofurov7 for taking care of this.

2021-09-28 11:59 UTC, kashifest commented
/cc @jan-est @maelk

2021-09-28 12:09 UTC, maelk commented
/lgtm

2021-09-28 12:10 UTC, merged